HMS/backend/backend/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hotel.urls')),

    path('accounts/', include('allauth.urls')),
]

HMS/backend/hotel/urls.py
from django.contrib import admin
from django.urls import path
from .views import RoomListView,BookingList,BookingView,RoomDetailView

app_name = 'hotel'

urlpatterns = [
    path('room_list/', RoomListView, name='RoomList'),
    path('booking_list/' ,BookingList.as_view(), name='BookingList'),
    path('book/', BookingView.as_view(), name='BookingView'),
    path('room/<category>/', RoomDetailView.as_view(), name='RoomDetailView')

]

HMS/backend/hotel/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Room(models.Model):
    ROOM_CATEGORIES = (
        ('YAC' ,'AC'),
        ('NAC' , 'NON-AC'),
        ('DEL' , 'DELUXE'),
        ('KIN' , 'KING'),
        ('QUE' , 'QUEEN'),
    )

    number = models.IntegerField()
    category = models.CharField(max_length = 3, choices = ROOM_CATEGORIES)
    beds = models.IntegerField()
    capacity = models.IntegerField()

    def __str__(self):
        return f'{self.number}. {self.category} with {self.beds} beds for {self.capacity} people'
    

class Booking(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()

    def __str__(self):
        return f'{self.user} has booked {self.room} from {self.check_in} to {self.check_out}'
    

HMS/backend/hotel/forms.py
from django import forms

class AvailabilityForm(forms.Form):

    check_in = forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT-%H:%M",])
    check_out = forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT-%H:%M",])
        

HMS/backend/hotel/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, HttpResponse
from django.views.generic import ListView, FormView, View
from .models import Room,Booking
from .forms import AvailabilityForm
from hotel.booking_functions.availability import check_availability
from django.urls import reverse

# Create your views here.


def RoomListView(request):
    room = Room.objects.all()[0]
    room_categories = dict(room.ROOM_CATEGORIES)
    room_values = room_categories.values()
    room_list = []

    for room_category in room_categories:
        room = room_categories.get(room_category)
        room_url = reverse('hotel:RoomDetailView', kwargs={
                           'category': room_category})

        room_list.append((room, room_url))
    context = {
        "room_list": room_list,
    }
    return render(request, 'htmlfiles/room_list_view.html', context)

class BookingList(ListView):
    model = Booking
    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_staff:
            booking_list = Booking.objects.all()
            return booking_list
        else:
            booking_list = Booking.objects.filter(user=self.request.user)
            return booking_list
        
class RoomDetailView(View):
    def get(self, request, *args, **kwargs):
        categories = self.kwargs.get('category', None)
        form = AvailabilityForm()
        room_list = Room.objects.filter(category=categories)
        
        if len(room_list) > 0:
          room = room_list[0]
          room_category = dict(room.ROOM_CATEGORIES).get(room.category)
          context = {
              'room_category' :room_category,
              'form' : form,
        }
          return render(request,'htmlfiles/room_details_view.html', context)
        else:
            return HttpResponse("Category does not exist")
      


    def post(self, request, *args, **kwargs):
        categories = self.kwargs.get('category', None)
        room_list = Room.objects.filter(category=categories)
        form  = AvailabilityForm(request.POST)

        if form.is_valid():
            data =form.cleaned_data
        available_rooms = []
        for room in room_list:
            if check_availability(room, data['check_in'],data['check_out']):
                available_rooms.append(room)

        if len(available_rooms) > 0:

            room = available_rooms[0]
            booking = Booking.objects.create(
                user = self.request.user,
                room = room,
                check_in = data['check_in'],
                check_out = data['check_out']
            )
            booking.save()
            return HttpResponse(booking)

        else:
            return HttpResponse('All of his category of rooms are booked !!')


class BookingView(FormView):
    form_class = AvailabilityForm
    template_name = 'availability.html'

    def form_valid(self, form):
        data = form.cleaned_data
        room_list = Room.objects.filter(category=data['room_categories'])
        available_rooms = []
        for room in room_list:
            if check_availability(room, data['check_in'],data['check_out']):
                available_rooms.append(room)

        if len(available_rooms) > 0:

            room = available_rooms[0]
            booking = Booking.objects.create(
                user = self.request.user,
                room = room,
                check_in = data['check_in'],
                check_out = data['check_out']
            )
            booking.save()
            return HttpResponse(booking)

        else:
            return HttpResponse('All of his category of rooms are booked !!')

    

HMS/backend/templates/availability.html
<html>
<head>
    <title>
        Book a room
    </title>
</head>
        
    <body>
        <form action="" method="post">
        {{form.as_p}}
        {% csrf_token %}
        <button type="submit">Book Room</button>

        </form>

    </body>
        

</html>

HMS/backend/templates/hotel/booking_list.html
<html>
<head>
    <title>
    </title>
</head>
<body>
 {% for booking in booking_list %}
 <h2>{{booking}}
    {%endfor%}
</body>
</html>

HMS/backend/templates/hotel/room_list.html
<html>
<head>
    <title>
    </title>
</head>
<body>
    {% for room in room_list %}
    <h2>{{room}}
       {%endfor%}
</body>
</html>

HMS/backend/templates/htmlfiles/room_details_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Room Detail</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>

    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'css/details.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/aboutus.css' %}" />

</head>

<body>

    <!-- Main Content -->
    <div class="content">

        <!-- Room Image -->
        <div class="image">
            <img
                src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
        </div>

        <!-- Room Details -->
        <div class="room">

            <!-- Div 1: Back to Home -->
            <div class="home">
                <a href="{% url 'hotel:RoomList' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
            </div>

            <!-- Div 2: Room Information -->
            <div class="room-info">
                <h1>{{room_category}}</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id optio rem saepe culpa architecto tempora
                    numquam debitis reiciendis! Quaerat laudantium consequuntur doloribus quod placeat consectetur
                    veniam,
                    rerum repellendus magnam labore. </p>
            </div>

            <!-- Div 3: Room Booking Form -->
            <form id="booking-form" action="" method="POST">

                {% csrf_token %}

                <!-- Input Div -->
                <div class="input-div">
                    <label for="id_check_in">Check In : </label>
                    <input type="datetime-local" id="id_check_in" name="check_in">
                </div>

                <!-- Input Div -->
                <div class="input-div">
                    <label for="id_check_out">Check Out : </label>
                    <input type="datetime-local" id="id_check_out" name="check_out">
                </div>

                <!-- Input Div -->
                <div class="input-div">
                    <button type="submit">Book the Room</button>
                </div>

            </form>

        </div> <!-- END Room Div -->

    </div> <!-- END Main Content Div -->

</body>

</html>

HMS/backend/templates/htmlfiles/room_list_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Hotelina</title>
    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'css/room_list_view.css' %}" />
    <link rel="stylesheet" href="{% static 'hotel/css/nav.css' %}" />
  </head>

  <body>
    <div class="container">
      <!-- Navbar -->
      {% comment %} <nav id="navbar">
        <div class="brand">
          <a href="https://www.darshandev.com">
            <h1 id="logo">Hotelina</h1>
          </a>
        </div>
        <div id="ham-div"  onclick="togglenav()">
            <img id="ham" src="https://img.icons8.com/material-rounded/24/000000/menu.png"/>
        </div>
        <div id="navlist-div" class="">
          <ul id="navlist" class="folding-nav hidden">
              {% if request.user.is_authenticated %}
            <li><a href="{% url 'account_logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'account_login' %}">Login</a></li>
            <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
            {% endif %}
          </ul>
        </div>
      </nav> {% endcomment %}

      <!-- Landing -->
      <div class="landing">
        <h1>Luxury <span>Re-Defined</span></h1>
        <img
          src="../static/hotel/img/hotel-1.jpg"
          id="landing-img"
          alt="Best Hotel in the World"
          srcset=""
        />
      </div>

      <h2>Rooms</h2>
      <!-- Main Content -->
      <div id="rooms">
        {% for room_category, room_url in room_list %}
        <div class="room">
          <a href="{{room_url}}">
          <img
            src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60"
          />
          <h2>{{room_category}}<h2>
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi
          </p>
          </a>
        </div>

        {% endfor %}
 
      </div>
    </div>
    <script src="{% static 'hotel/js/nav.js' %}"></script>
  </body>
</html>